# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{teeth}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel DeLeo"]
  s.date = %q{2010-05-14}
  s.description = %q{Fast log file parsing in Ruby}
  s.email = %q{ddeleo@basecommander.net}
  s.extensions = ["ext/scan_apache_logs/extconf.rb", "ext/scan_rails_logs/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "ext/scan_apache_logs/extconf.rb",
     "ext/scan_apache_logs/scan_apache_logs.yy",
     "ext/scan_apache_logs/scan_apache_logs.yy.c",
     "ext/scan_rails_logs/extconf.rb",
     "ext/scan_rails_logs/scan_rails_logs.yy",
     "ext/scan_rails_logs/scan_rails_logs.yy.c",
     "lib/teeth.rb",
     "lib/teeth/rule_statement.rb",
     "lib/teeth/scanner.rb",
     "lib/teeth/scanner_definition.rb",
     "lib/teeth/scanner_definitions/scan_apache_logs.rb",
     "lib/teeth/scanner_definitions/scan_rails_logs.rb",
     "lib/teeth/templates/tokenizer.yy.erb",
     "spec/fixtures/rails_1x.log",
     "spec/fixtures/rails_22.log",
     "spec/fixtures/rails_22_cached.log",
     "spec/fixtures/rails_unordered.log",
     "spec/playground/scan_rails_logs.rb",
     "spec/playground/show_apache_processing.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/rule_statement_spec.rb",
     "spec/unit/scan_apache_spec.rb",
     "spec/unit/scan_rails_logs_spec.rb",
     "spec/unit/scaner_definition_spec.rb",
     "spec/unit/scanner_spec.rb",
     "teeth.gemspec"
  ]
  s.homepage = %q{http://github.com/danielsdeleo/teeth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = [["lib"]]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Fast log file parsing in Ruby}
  s.test_files = [
    "spec/playground/scan_rails_logs.rb",
     "spec/playground/show_apache_processing.rb",
     "spec/spec_helper.rb",
     "spec/unit/rule_statement_spec.rb",
     "spec/unit/scan_apache_spec.rb",
     "spec/unit/scan_rails_logs_spec.rb",
     "spec/unit/scaner_definition_spec.rb",
     "spec/unit/scanner_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

